@startuml

participant "_ProductionConfig" as _ProductionConfig
participant "SynTracer" as SynTracer
participant "SynFormatter" as SynFormatter
participant "_LiteralGenericAlias" as _LiteralGenericAlias
participant "SynFiletransfer" as SynFiletransfer
participant "_SixMetaPathImporter" as _SixMetaPathImporter
participant "PushManager" as PushManager
participant "SynLogger" as SynLogger
participant "SyslogHandler" as SyslogHandler
participant "ConsoleHandler" as ConsoleHandler
participant "VendorImporter" as VendorImporter
participant "SynTransport" as SynTransport

SynFiletransfer -> SynFiletransfer : delete_users()
SynFiletransfer -> SynFiletransfer : delete_user()
SynFiletransfer -> SynFiletransfer : delete_folder()
SynFiletransfer -> SynFiletransfer : create_users()
SynFiletransfer -> SynFiletransfer : add_user_to_os()
SynFiletransfer -> SynFiletransfer : create_user_dirs_first_level()
SynFiletransfer -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynFiletransfer : add_user_to_os()
SynFiletransfer -> SynFiletransfer : create_user_dirs_first_level()
SynFiletransfer -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynFiletransfer : delete_rules_dirs()
SynFiletransfer -> SynFiletransfer : delete_user_rules_dirs()
SynFiletransfer -> SynFiletransfer : get_user_rules_to_delete()
SynFiletransfer -> SynFiletransfer : umount_incoming()
SynFiletransfer -> SynFiletransfer : delete_folder()
SynFiletransfer -> SynFiletransfer : umount_incoming()
SynFiletransfer -> SynFiletransfer : delete_folder()
SynFiletransfer -> SynFiletransfer : umount_incoming()
SynFiletransfer -> SynFiletransfer : delete_folder()
SynFiletransfer -> SynFiletransfer : create_rule_dirs()
SynFiletransfer -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynLogger : __init__()
SynLogger -> SynLogger : _add_handlers()
SynLogger -> ConsoleHandler : __init__()
ConsoleHandler -> SynFormatter : __init__()
SynFormatter -> SyslogHandler : __init__()
SyslogHandler -> SynFormatter : __init__()
SynFormatter -> SynFiletransfer : mount_incoming()
SynFiletransfer -> SynFiletransfer : manage_pushes()
SynFiletransfer -> PushManager : __init__()
PushManager -> SynFiletransfer : add_ssh_pubkeys()
SynFiletransfer -> SynTracer : stop_trace()
SynTracer -> SynTransport : __init__()
SynTransport -> _ProductionConfig : __init__()
_ProductionConfig -> _LiteralGenericAlias : __eq__()
_LiteralGenericAlias -> _ProductionConfig : set_setup_attr()
_ProductionConfig -> _LiteralGenericAlias : __eq__()
_LiteralGenericAlias -> SynTransport : apply_transport_config()
SynTransport -> VendorImporter : find_module()
VendorImporter -> _SixMetaPathImporter : find_module()
_SixMetaPathImporter -> SynTransport : get_slots_to_delete()
SynTransport -> SynTransport : slots_to_run()
SynTransport -> SynTransport : get_slots_to_check()
SynTransport -> SynTransport : slots_to_reload()
SynTransport -> SynTransport : get_slots_to_check()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_run()
SynTransport -> SynTransport : actual_slots()
SynTransport -> SynTransport : check_active()
SynTransport -> SynTransport : is_need_to_reload()

@enduml
